### ISSUE TITLE
Test linking issues to changelogs

### ISSUE THREAD

**Issue by inFocus7** [inFocus7/changelog-files-action#1]
We should test that when adding issues to the changelog it gets rendered correctly based on the example provided in the README + https://github.com/inFocus7/changelog-files-action-tester.

```yml
fix:
  - fixes blah <issue link>
```
```markdown
## Fixes
- Fixes Blah <issue link>
```

Maybe would require a redesign + a major release to support something along the lines of
```yml
fix:
  - description: blah
    issueLink: <link>
  - description: blah2
    issueLink: <link2>
```
```markdown
## Fixes
- blah (<link>)
- blah2 (<link2>)
